// frontend/src/components/Employee/ViewAllEmployees.tsx
import React, { useEffect, useState } from 'react';
import { getEmployeesList } from '../../services/EmployeeService';
import IEmployeeData from '../../models/Employee';
import './ViewAllEmployees.css';

const ViewAllEmployees = () => {
    const [employees, setEmployees] = useState<IEmployeeData[]>([]);

    useEffect(() => {
        getEmployeesList()
            .then(data => {
                setEmployees(data);
            })
            .catch(error => console.error(error));
    }, []);

    return (
      <div className="container container-custom mt-3">
          <h2>Darbinieku saraksts</h2>
          <table className="table table-hover">
              <thead className="thead-dark">
                  <tr>
                      <th>ID</th>
                      <th>Vārds</th>
                      <th>Uzvārds</th>
                      <th>Amats</th>
                      <th>Ir ievēlēts</th>
                      <th>Darba līgums un datums</th>
                      <th>Nodaļa</th>
                  </tr>
              </thead>
              <tbody>
                  {employees.map(employee => (
                      <tr key={employee.idEmployee}>
                          <td>{employee.idEmployee}</td>
                          <td>{employee.name}</td>
                          <td>{employee.surname}</td>
                          <td>{employee.position}</td>
                          <td>{employee.elected ? 'Jā' : 'Nē'}</td>
                          <td>{employee.workContractNoDate}</td>
                          <td>{employee.departmentName}</td>
                          <td>
                              <button className="btn btn-outline-success me-2">Labot</button>
                              <button className="btn btn-outline-danger">Dzēst</button>
                          </td>
                      </tr>
                  ))}
              </tbody>
          </table>
          <button className="btn btn-outline-dark">Pievienot</button>
      </div>
  );
};

export default ViewAllEmployees;

// frontend/src/app/components/employee/view-all-employees/view-all-employees.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Employee } from '../../../models/employee.model';
import { EmployeeService } from '../../../services/employee.service';

@Component({
  selector: 'app-view-all-employees',
  templateUrl: './view-all-employees.component.html',
  styleUrls: ['./view-all-employees.component.css']
})
export class ViewAllEmployeesComponent implements OnInit {
  employees: Employee[] = [];

  constructor(private employeeService: EmployeeService, private router: Router) { }

  ngOnInit(): void {
    this.getEmployees();
  }

  private getEmployees() {
    this.employeeService.getEmployeesList().subscribe(data => {
      this.employees = data;
    });
  }

  navigateToUpdate(employee: Employee): void {
    this.router.navigate(['/update-employee'], { state: { employee } });
  }
}

<div class="container container-custom mt-3">
    <h2>Darbinieku saraksts</h2>
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th>ID</th>
          <th>Vārds</th>
          <th>Uzvārds</th>
          <th>Amats</th>
          <th>Ir ievēlēts</th>
          <th>Darba līgums un datums</th>
          <th>Nodaļa</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let employee of employees">
          <td>{{ employee.idEmployee }}</td>
          <td>{{ employee.name }}</td>
          <td>{{ employee.surname }}</td>
          <td>{{ employee.position }}</td>
          <td>{{ employee.elected ? 'Jā' : 'Nē' }}</td>
          <td>{{ employee.workContractNoDate }}</td>
          <td>{{ employee.departmentName }}</td>
          
          <td>
            <button class="btn btn-outline-success me-2" (click)="navigateToUpdate(employee)">Labot</button>
            <button class="btn btn-outline-danger">Dzēst</button>
          </td>
        </tr>
      </tbody>
    </table>
      <button class="btn btn-outline-dark">Pievienot</button>
    
  </div>
